services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - example.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - spring
    depends_on:
      - main-service
      - book



  main-service:
    image: bnazar00/main-service:latest
    container_name: main-service
    ports:
      - "8081:8081"
    env_file:
      - example.env
    networks:
      - spring
      - postgres
    depends_on:
      - postgres

  book:
    image: bnazar00/book:latest
    container_name: book
    ports:
      - "8082:8082"
    env_file:
      - example.env
    networks:
      - spring
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
