spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      show-sql: true
    properties:
      hibernate:
#        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
application:
  security:
    jwt:
      access-token-secret: ${JWT_ACCESS_SECRET}
      access-token-expiration-time-in-minutes: 1440
